### ISSUE TITLE
Useful command aliases

### ISSUE THREAD

**Issue by liquidnya** [ToransuShoujo/quesoqueue_plus#14]
I would suggest the following command aliases for `!odds`/`!weightedchance`:

- `!chance`
- `!chances`

And I would suggest the following command aliases for `!submitted`:

- `!entry`
- `!mylevel`
- `!mylvl`

The `!entry`, `!mylevel` and `!mylvl` commands are already actively being used in morpha00's and scherbie_'s streams.

**Comment by ToransuShoujo** [comment]
These aliases have been added as of commit 49ef02e662925cc597d2cd095449c0dc55b17011.

**Comment by ToransuShoujo** [comment]
These aliases have been added as of commit 49ef02e662925cc597d2cd095449c0dc55b17011.
