### ISSUE TITLE
Error handling of chatters resource

### ISSUE THREAD

**Issue by liquidnya** [ToransuShoujo/quesoqueue_plus#8]
If there is an error with twitch's chatters resource the whole queue crashes.
Prevent a crash by caching it's previous result and serving that instead of on error.
As well as making sure to never use a cached result for the `!level`, `!next`, etc. commands (or at least trying to and in case of an error still fallback to the cache to prevent a crash).

**Comment by liquidnya** [comment]
Ideally the chatters response would be cached similar to https://github.com/mistval/node-fetch-cache/issues/21 (not resolved yet).

A good option would be to cache the response for one minute, and then make another request after that minute When that request fails use the cache still and log an error to the console that the online status might be inaccurate! (This makes the queue still usable and not crash but less accurate)

Also for some critical chat commands, ignore the cache anyways (except when the request fails); for example when `!level` is called, the resource should be called instead of using the cache.

**Comment by ToransuShoujo** [comment]
This bug has been (theoretically) resolved as of commit 4aac6a45beb13fe66e93f14403576d5628baf7bd.
